service: scalegpt-back-api

provider:
  name: aws
  deploymentMethod: direct
  runtime: nodejs18.x
  stage: production
  region: us-east-1
  environment:
    MONGODB_URI: mongodb://mongouser:Hxv6DS%26ZhY4prM@ec2-54-227-72-167.compute-1.amazonaws.com:27017/local?authSource=admin
    REFRESH_TOKEN: 18339d93-49f7-4326-a498-70f35f2e0695
    ACCESS_TOKEN: 7e9ff4c4-954e-4a03-931c-5de8c8b22977
    CLIENT_ID: tmM2YXmM
    SECRET_KEY: 11f8a63f2ad33b98dbd95d42d4fb70fe8f3d37f1
    CORP_ID: 1005
    JWT_SECRET: 2139128312938123
    NODE_ENV: production

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

package:
  individually: true 
  
functions:
  app:
    handler: index.handler
    timeout: 30 #seconds
    events:
      - http:
          path: /
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
              - Access-Token
              - Sec-Ch-Ua
              - Sec-Ch-Ua-Mobile
              - Sec-Ch-Ua-Platform
              - Referer
              - Accept
            methods:
              - OPTIONS
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
              - Access-Token
              - Sec-Ch-Ua
              - Sec-Ch-Ua-Mobile
              - Sec-Ch-Ua-Platform
              - Referer
              - Accept
            methods:
              - OPTIONS
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
    # patterns:
    # - '!node_modules/**'
    # - '!test/**'
    # - 'handler.js'
    # - 'libs/**'

custom:
  dotenv:
    path: ./.env
  serverless-offline:
    httpPort: 3000
  webpack:
    webpackConfig: './webpack.config.js'  # Caminho para o arquivo de configuração do webpack
    includeModules: true  # Para incluir node_modules no bundle, se necessário