openapi: 3.0.0
components:
  schemas: {}
  securitySchemes: {}
info:
  title: API Serverless scalegpt-back
  description: Esta é a documentação API do meu projeto Serverless.
  version: 1.0.0
paths: {}
